### ISSUE TITLE
Closing the wallet app does not lock it

### ISSUE THREAD

**Issue by quentin-legraverend** [redDwarf03/archethic_mobile_wallet#948] opened 2024-05-18 17:52 UTC
### Describe the problem you discovered

Wallet version: 2.3.6b512
macOS version: 13.3.1

It's not really a bug, as the app behaviour seems consistant, it's more an implementation choice / discussion.

Actual "problem"
1. Launch and unlock your wallet
2. Close the wallet
3. Open it again (before the auto-lock timer): the wallet is still unlocked

Related to #941 

### Describe the solution you'd like

May be this could be fine-tuned in the settings (auto-lock on close disabled) but IMO, on a security perspective, it makes more sense to lock it by default.

**Comment by Chralu** [comment] 2024-05-20 08:24
Hi @quentin-legraverend ,

thanks for your tickets. This is really helpful 🙏

**Comment by Chralu** [comment] 2024-05-21 09:39
Hi @quentin-legraverend,

indeed this is not a bug.
Nevertheless, I understand that behavior might be confusing.

I close this issue, but discussion for a solution is open on #941 .

**Closed as completed by Chralu** 2024-05-21 09:39 UTC
Labels: bug, feat:lock
